//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BidWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class BidingInfo
    {
        public int Id { get; set; }
        public string ProductCode { get; set; }
        public string UserName { get; set; }
        public double MaxBid { get; set; }
        public string DateHeBid { get; set; }
    }
}
