//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BidWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInfo
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string Category { get; set; }
        public string ProductImage { get; set; }
        public double MinimumBid { get; set; }
        public string UserName { get; set; }
        public string LastDate { get; set; }
        public string Details { get; set; }
        public string ProductCode { get; set; }
    }
}
